# Logistic Regression analysis

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np

In [3]:
lr=pd.read_csv('/content/drive/MyDrive/Python Datasets/Social_Network_Ads(1).csv')

In [4]:
lr.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [5]:
lr.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [6]:
# Split data into dependent and independent variables
X=lr.iloc[:,[1,2,3]].values
y=lr.iloc[:,4].values

In [9]:
print(X)

[[1 19 19000]
 [1 35 20000]
 [0 26 43000]
 ...
 [0 50 20000]
 [1 36 33000]
 [0 49 36000]]


In [8]:
# Convert Categorical variables into numerical Variable
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,0]=le.fit_transform(X[:,0])

In [10]:
# Split data into training and testing dataset
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [11]:
print(X_train)

[[1 26 15000]
 [1 60 102000]
 [0 38 112000]
 [1 40 107000]
 [0 42 53000]
 [1 35 59000]
 [1 48 41000]
 [0 48 134000]
 [0 38 113000]
 [1 29 148000]
 [0 26 15000]
 [1 60 42000]
 [1 24 19000]
 [1 42 149000]
 [0 46 96000]
 [1 28 59000]
 [1 39 96000]
 [1 28 89000]
 [1 41 72000]
 [1 45 26000]
 [0 33 69000]
 [0 20 82000]
 [1 31 74000]
 [1 42 80000]
 [0 35 72000]
 [0 33 149000]
 [1 40 71000]
 [0 51 146000]
 [1 46 79000]
 [1 35 75000]
 [1 38 51000]
 [0 36 75000]
 [0 37 78000]
 [1 38 61000]
 [0 60 108000]
 [0 20 82000]
 [1 57 74000]
 [1 42 65000]
 [1 26 80000]
 [1 46 117000]
 [1 35 61000]
 [0 21 68000]
 [0 28 44000]
 [1 41 87000]
 [0 37 33000]
 [1 27 90000]
 [1 39 42000]
 [1 28 123000]
 [0 31 118000]
 [1 25 87000]
 [0 35 71000]
 [1 37 70000]
 [1 35 39000]
 [1 47 23000]
 [0 35 147000]
 [0 48 138000]
 [1 26 86000]
 [1 25 79000]
 [0 52 138000]
 [1 51 23000]
 [0 35 60000]
 [0 33 113000]
 [1 30 107000]
 [1 48 33000]
 [0 41 80000]
 [0 48 96000]
 [1 31 18000]
 [0 31 71000]
 [1 43 129000]
 [0 59 76000]
 

In [13]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [14]:
#implement logistic regression
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression()

In [15]:
y_pred=classifier.predict(X_test)

In [16]:
#test the model- create confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[74  5]
 [ 8 33]]


In [18]:
# Measure Accuracy, Precision, Recall and F1 Score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Accuracy: 0.8916666666666667
Precision: 0.868421052631579
Recall: 0.8048780487804879
F1 Score: 0.8354430379746836


# Gaussian NB algorithm

In [20]:
# implement gaussian NB algo
from sklearn.naive_bayes import GaussianNB
classifierNB=GaussianNB()
classifierNB.fit(X_train,y_train)

GaussianNB()

In [21]:
y_predNB=classifierNB.predict(X_test)


In [22]:
# Confusion Matrix for Gaussion NB
from sklearn.metrics import confusion_matrix
cmNB=confusion_matrix(y_test,y_predNB)
print(cmNB)

[[76  3]
 [ 8 33]]


In [23]:
# Measure Accuracy, Precision, recall and f1 score for Gaussion NB
accuracyNB = accuracy_score(y_test, y_predNB)
precisionNB = precision_score(y_test, y_predNB)
recallNB = recall_score(y_test, y_predNB)
f1NB = f1_score(y_test, y_predNB)
print("AccuracyNB:", accuracyNB)
print("PrecisionNB:", precisionNB)
print("RecallNB:", recallNB)
print("F1 ScoreNB:", f1NB)

AccuracyNB: 0.9083333333333333
PrecisionNB: 0.9166666666666666
RecallNB: 0.8048780487804879
F1 ScoreNB: 0.8571428571428571


In [24]:
# Compare results of Logistic regression and gaussion NB algo
print("Logistic Regression Results:")
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("\nGaussian NB Results:")
print("AccuracyNB:", accuracyNB)
print("PrecisionNB:", precisionNB)
print("RecallNB:", recallNB)
print("F1 ScoreNB:", f1NB)


Logistic Regression Results:
Accuracy: 0.8916666666666667
Precision: 0.868421052631579
Recall: 0.8048780487804879
F1 Score: 0.8354430379746836

Gaussian NB Results:
AccuracyNB: 0.9083333333333333
PrecisionNB: 0.9166666666666666
RecallNB: 0.8048780487804879
F1 ScoreNB: 0.8571428571428571
